import Foundation
import Testing
import UIKit

@testable import WakuwakuChizu

/// The painted specialty cards (CLAUDE.md §4).
///
/// `art` is generated by `tools/build_card_art.py` and committed, so the JSON
/// and the asset catalog are two files that have to agree. Nothing at build
/// time enforces that, which is what these are for: a renamed imageset or a
/// hand-edited card entry shows up here rather than as a キラカード that renders
/// blank on a child's iPad.
@MainActor
struct CardArtTests {

    private var catalog: CardCatalog { MapDataTests.catalog }

    private var illustrated: [SpecialtyCard] {
        catalog.all.filter { $0.art != nil }
    }

    @Test func someCardsAreIllustrated() {
        #expect(!illustrated.isEmpty, "no card has art; did build_card_art.py run?")
        #expect(illustrated.count <= catalog.count)
    }

    /// The one that actually catches things: an asset name in the JSON that no
    /// longer exists in the bundle.
    @Test func everyArtNameResolvesToABundledImage() throws {
        for card in illustrated {
            let name = try #require(card.art)
            #expect(UIImage(named: name) != nil,
                    "card \(card.id) (\(card.nameKanji)) points at missing asset \(name)")
        }
    }

    @Test func artNamesAreUnique() {
        let names = illustrated.compactMap(\.art)
        #expect(Set(names).count == names.count, "two cards share one illustration")
    }

    /// The generator derives the asset name from the card id, so a mismatch
    /// means the JSON was edited by hand and the pair has drifted.
    @Test func artNameMatchesItsCardID() throws {
        for card in illustrated {
            #expect(card.art == "card-\(card.id)",
                    "\(card.id) has art named \(card.art ?? "nil")")
        }
    }

    /// Art is square: the chip lays it out in a 1:1 frame, and a stray aspect
    /// ratio would letterbox one card and not the others.
    @Test func illustrationsAreSquare() throws {
        for card in illustrated {
            let name = try #require(card.art)
            let image = try #require(UIImage(named: name))
            #expect(image.size.width == image.size.height,
                    "\(name) is \(image.size), not square")
        }
    }

    /// A card without art is a supported state, not a defect — most of the 141
    /// are still emoji-only, and they must keep working.
    @Test func cardsWithoutArtDecodeFine() {
        let plain = catalog.all.filter { $0.art == nil }
        #expect(!plain.isEmpty)
        for card in plain {
            #expect(!card.emoji.isEmpty, "\(card.id) has neither art nor emoji")
        }
    }
}
